// Generated by tools/units-generator. Edit catalog files in tools/units-generator and run mise run
// generate:units.
@file:JvmSynthetic

package org.maplibre.spatialk.units.extensions

import kotlin.Double
import kotlin.Int
import kotlin.jvm.JvmSynthetic
import org.maplibre.spatialk.units.Area
import org.maplibre.spatialk.units.Length
import org.maplibre.spatialk.units.Rotation
import org.maplibre.spatialk.units.catalog.Angles.ArcMinutes
import org.maplibre.spatialk.units.catalog.Angles.ArcSeconds
import org.maplibre.spatialk.units.catalog.Angles.Degrees
import org.maplibre.spatialk.units.catalog.Angles.Radians
import org.maplibre.spatialk.units.catalog.Angles.Turns
import org.maplibre.spatialk.units.catalog.Customary.Acres
import org.maplibre.spatialk.units.catalog.Customary.Feet
import org.maplibre.spatialk.units.catalog.Customary.Inches
import org.maplibre.spatialk.units.catalog.Customary.LandMiles
import org.maplibre.spatialk.units.catalog.Customary.SquareFeet
import org.maplibre.spatialk.units.catalog.Customary.SquareMiles
import org.maplibre.spatialk.units.catalog.Customary.SquareYards
import org.maplibre.spatialk.units.catalog.Customary.Yards
import org.maplibre.spatialk.units.catalog.Metric.Centimeters
import org.maplibre.spatialk.units.catalog.Metric.Hectares
import org.maplibre.spatialk.units.catalog.Metric.Kilometers
import org.maplibre.spatialk.units.catalog.Metric.Meters
import org.maplibre.spatialk.units.catalog.Metric.Millimeters
import org.maplibre.spatialk.units.catalog.Metric.SquareKilometers
import org.maplibre.spatialk.units.catalog.Metric.SquareMeters
import org.maplibre.spatialk.units.catalog.Nautical.NauticalMiles

/**
 * Creates a [Area] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Metric.SquareMeters].
 */
public inline val Double.squareMeters: Area
    get() = toArea(SquareMeters)

/**
 * Creates a [Area] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Metric.SquareMeters].
 */
public inline val Int.squareMeters: Area
    get() = toDouble().toArea(SquareMeters)

/**
 * Returns this [Area] as a scalar value in
 * [org.maplibre.spatialk.units.catalog.Metric.SquareMeters].
 */
public inline val Area.inSquareMeters: Double
    get() = toDouble(SquareMeters)

/**
 * Creates a [Area] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Metric.SquareKilometers].
 */
public inline val Double.squareKilometers: Area
    get() = toArea(SquareKilometers)

/**
 * Creates a [Area] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Metric.SquareKilometers].
 */
public inline val Int.squareKilometers: Area
    get() = toDouble().toArea(SquareKilometers)

/**
 * Returns this [Area] as a scalar value in
 * [org.maplibre.spatialk.units.catalog.Metric.SquareKilometers].
 */
public inline val Area.inSquareKilometers: Double
    get() = toDouble(SquareKilometers)

/**
 * Creates a [Length] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Metric.Millimeters].
 */
public inline val Double.millimeters: Length
    get() = toLength(Millimeters)

/**
 * Creates a [Length] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Metric.Millimeters].
 */
public inline val Int.millimeters: Length
    get() = toDouble().toLength(Millimeters)

/**
 * Returns this [Length] as a scalar value in
 * [org.maplibre.spatialk.units.catalog.Metric.Millimeters].
 */
public inline val Length.inMillimeters: Double
    get() = toDouble(Millimeters)

/**
 * Creates a [Length] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Metric.Centimeters].
 */
public inline val Double.centimeters: Length
    get() = toLength(Centimeters)

/**
 * Creates a [Length] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Metric.Centimeters].
 */
public inline val Int.centimeters: Length
    get() = toDouble().toLength(Centimeters)

/**
 * Returns this [Length] as a scalar value in
 * [org.maplibre.spatialk.units.catalog.Metric.Centimeters].
 */
public inline val Length.inCentimeters: Double
    get() = toDouble(Centimeters)

/**
 * Creates a [Length] from a scalar value in [org.maplibre.spatialk.units.catalog.Metric.Meters].
 */
public inline val Double.meters: Length
    get() = toLength(Meters)

/**
 * Creates a [Length] from a scalar value in [org.maplibre.spatialk.units.catalog.Metric.Meters].
 */
public inline val Int.meters: Length
    get() = toDouble().toLength(Meters)

/**
 * Returns this [Length] as a scalar value in [org.maplibre.spatialk.units.catalog.Metric.Meters].
 */
public inline val Length.inMeters: Double
    get() = toDouble(Meters)

/**
 * Creates a [Length] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Metric.Kilometers].
 */
public inline val Double.kilometers: Length
    get() = toLength(Kilometers)

/**
 * Creates a [Length] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Metric.Kilometers].
 */
public inline val Int.kilometers: Length
    get() = toDouble().toLength(Kilometers)

/**
 * Returns this [Length] as a scalar value in
 * [org.maplibre.spatialk.units.catalog.Metric.Kilometers].
 */
public inline val Length.inKilometers: Double
    get() = toDouble(Kilometers)

/**
 * Creates a [Area] from a scalar value in [org.maplibre.spatialk.units.catalog.Metric.Hectares].
 */
public inline val Double.hectares: Area
    get() = toArea(Hectares)

/**
 * Creates a [Area] from a scalar value in [org.maplibre.spatialk.units.catalog.Metric.Hectares].
 */
public inline val Int.hectares: Area
    get() = toDouble().toArea(Hectares)

/**
 * Returns this [Area] as a scalar value in [org.maplibre.spatialk.units.catalog.Metric.Hectares].
 */
public inline val Area.inHectares: Double
    get() = toDouble(Hectares)

/**
 * Creates a [Area] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Customary.SquareFeet].
 */
public inline val Double.squareFeet: Area
    get() = toArea(SquareFeet)

/**
 * Creates a [Area] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Customary.SquareFeet].
 */
public inline val Int.squareFeet: Area
    get() = toDouble().toArea(SquareFeet)

/**
 * Returns this [Area] as a scalar value in
 * [org.maplibre.spatialk.units.catalog.Customary.SquareFeet].
 */
public inline val Area.inSquareFeet: Double
    get() = toDouble(SquareFeet)

/**
 * Creates a [Area] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Customary.SquareYards].
 */
public inline val Double.squareYards: Area
    get() = toArea(SquareYards)

/**
 * Creates a [Area] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Customary.SquareYards].
 */
public inline val Int.squareYards: Area
    get() = toDouble().toArea(SquareYards)

/**
 * Returns this [Area] as a scalar value in
 * [org.maplibre.spatialk.units.catalog.Customary.SquareYards].
 */
public inline val Area.inSquareYards: Double
    get() = toDouble(SquareYards)

/**
 * Creates a [Area] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Customary.SquareMiles].
 */
public inline val Double.squareMiles: Area
    get() = toArea(SquareMiles)

/**
 * Creates a [Area] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Customary.SquareMiles].
 */
public inline val Int.squareMiles: Area
    get() = toDouble().toArea(SquareMiles)

/**
 * Returns this [Area] as a scalar value in
 * [org.maplibre.spatialk.units.catalog.Customary.SquareMiles].
 */
public inline val Area.inSquareMiles: Double
    get() = toDouble(SquareMiles)

/**
 * Creates a [Area] from a scalar value in [org.maplibre.spatialk.units.catalog.Customary.Acres].
 */
public inline val Double.acres: Area
    get() = toArea(Acres)

/**
 * Creates a [Area] from a scalar value in [org.maplibre.spatialk.units.catalog.Customary.Acres].
 */
public inline val Int.acres: Area
    get() = toDouble().toArea(Acres)

/**
 * Returns this [Area] as a scalar value in [org.maplibre.spatialk.units.catalog.Customary.Acres].
 */
public inline val Area.inAcres: Double
    get() = toDouble(Acres)

/**
 * Creates a [Length] from a scalar value in [org.maplibre.spatialk.units.catalog.Customary.Inches].
 */
public inline val Double.inches: Length
    get() = toLength(Inches)

/**
 * Creates a [Length] from a scalar value in [org.maplibre.spatialk.units.catalog.Customary.Inches].
 */
public inline val Int.inches: Length
    get() = toDouble().toLength(Inches)

/**
 * Returns this [Length] as a scalar value in
 * [org.maplibre.spatialk.units.catalog.Customary.Inches].
 */
public inline val Length.inInches: Double
    get() = toDouble(Inches)

/**
 * Creates a [Length] from a scalar value in [org.maplibre.spatialk.units.catalog.Customary.Feet].
 */
public inline val Double.feet: Length
    get() = toLength(Feet)

/**
 * Creates a [Length] from a scalar value in [org.maplibre.spatialk.units.catalog.Customary.Feet].
 */
public inline val Int.feet: Length
    get() = toDouble().toLength(Feet)

/**
 * Returns this [Length] as a scalar value in [org.maplibre.spatialk.units.catalog.Customary.Feet].
 */
public inline val Length.inFeet: Double
    get() = toDouble(Feet)

/**
 * Creates a [Length] from a scalar value in [org.maplibre.spatialk.units.catalog.Customary.Yards].
 */
public inline val Double.yards: Length
    get() = toLength(Yards)

/**
 * Creates a [Length] from a scalar value in [org.maplibre.spatialk.units.catalog.Customary.Yards].
 */
public inline val Int.yards: Length
    get() = toDouble().toLength(Yards)

/**
 * Returns this [Length] as a scalar value in [org.maplibre.spatialk.units.catalog.Customary.Yards].
 */
public inline val Length.inYards: Double
    get() = toDouble(Yards)

/**
 * Creates a [Length] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Customary.LandMiles].
 */
public inline val Double.miles: Length
    get() = toLength(LandMiles)

/**
 * Creates a [Length] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Customary.LandMiles].
 */
public inline val Int.miles: Length
    get() = toDouble().toLength(LandMiles)

/**
 * Returns this [Length] as a scalar value in
 * [org.maplibre.spatialk.units.catalog.Customary.LandMiles].
 */
public inline val Length.inMiles: Double
    get() = toDouble(LandMiles)

/**
 * Creates a [Rotation] from a scalar value in [org.maplibre.spatialk.units.catalog.Angles.Radians].
 */
public inline val Double.radians: Rotation
    get() = toRotation(Radians)

/**
 * Creates a [Rotation] from a scalar value in [org.maplibre.spatialk.units.catalog.Angles.Radians].
 */
public inline val Int.radians: Rotation
    get() = toDouble().toRotation(Radians)

/**
 * Returns this [Rotation] as a scalar value in
 * [org.maplibre.spatialk.units.catalog.Angles.Radians].
 */
public inline val Rotation.inRadians: Double
    get() = toDouble(Radians)

/**
 * Creates a [Rotation] from a scalar value in [org.maplibre.spatialk.units.catalog.Angles.Degrees].
 */
public inline val Double.degrees: Rotation
    get() = toRotation(Degrees)

/**
 * Creates a [Rotation] from a scalar value in [org.maplibre.spatialk.units.catalog.Angles.Degrees].
 */
public inline val Int.degrees: Rotation
    get() = toDouble().toRotation(Degrees)

/**
 * Returns this [Rotation] as a scalar value in
 * [org.maplibre.spatialk.units.catalog.Angles.Degrees].
 */
public inline val Rotation.inDegrees: Double
    get() = toDouble(Degrees)

/**
 * Creates a [Rotation] from a scalar value in [org.maplibre.spatialk.units.catalog.Angles.Turns].
 */
public inline val Double.turns: Rotation
    get() = toRotation(Turns)

/**
 * Creates a [Rotation] from a scalar value in [org.maplibre.spatialk.units.catalog.Angles.Turns].
 */
public inline val Int.turns: Rotation
    get() = toDouble().toRotation(Turns)

/**
 * Returns this [Rotation] as a scalar value in [org.maplibre.spatialk.units.catalog.Angles.Turns].
 */
public inline val Rotation.inTurns: Double
    get() = toDouble(Turns)

/**
 * Creates a [Rotation] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Angles.ArcMinutes].
 */
public inline val Double.arcMinutes: Rotation
    get() = toRotation(ArcMinutes)

/**
 * Creates a [Rotation] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Angles.ArcMinutes].
 */
public inline val Int.arcMinutes: Rotation
    get() = toDouble().toRotation(ArcMinutes)

/**
 * Returns this [Rotation] as a scalar value in
 * [org.maplibre.spatialk.units.catalog.Angles.ArcMinutes].
 */
public inline val Rotation.inArcMinutes: Double
    get() = toDouble(ArcMinutes)

/**
 * Creates a [Rotation] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Angles.ArcSeconds].
 */
public inline val Double.arcSeconds: Rotation
    get() = toRotation(ArcSeconds)

/**
 * Creates a [Rotation] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Angles.ArcSeconds].
 */
public inline val Int.arcSeconds: Rotation
    get() = toDouble().toRotation(ArcSeconds)

/**
 * Returns this [Rotation] as a scalar value in
 * [org.maplibre.spatialk.units.catalog.Angles.ArcSeconds].
 */
public inline val Rotation.inArcSeconds: Double
    get() = toDouble(ArcSeconds)

/**
 * Creates a [Length] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Nautical.NauticalMiles].
 */
public inline val Double.nauticalMiles: Length
    get() = toLength(NauticalMiles)

/**
 * Creates a [Length] from a scalar value in
 * [org.maplibre.spatialk.units.catalog.Nautical.NauticalMiles].
 */
public inline val Int.nauticalMiles: Length
    get() = toDouble().toLength(NauticalMiles)

/**
 * Returns this [Length] as a scalar value in
 * [org.maplibre.spatialk.units.catalog.Nautical.NauticalMiles].
 */
public inline val Length.inNauticalMiles: Double
    get() = toDouble(NauticalMiles)
