// Generated by tools/units-generator. Edit Catalog.kt and run mise run generate:units.
package org.maplibre.spatialk.units

import kotlin.jvm.JvmField

/** Chinese market land measures used in official agricultural reporting. */
public data object China {
    /**
     * Definition: 1 market mu = 1/15 hectare = 2000/3 square meters.
     *
     * See
     * [China National Bureau of Statistics](https://www.stats.gov.cn/hd/cjwtjd/202302/t20230207_1902270.html).
     */
    @JvmField public val MarketMu: AreaUnit = AreaUnit(666.6666666666666, "mu")
}
