// Generated by tools/units-generator. Edit Catalog.kt and run mise run generate:units.
package org.maplibre.spatialk.units

import kotlin.jvm.JvmField

/** German legal units used in legacy coordinate systems, including Namibia's Schwarzeck datum. */
public data object Germany {
    /**
     * Definition: German legal meter, EPSG 9031: 1.0000135965 SI meters.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val LegalMeters: LengthUnit = LengthUnit(1.0000135965, "m")
}
