// Generated by tools/units-generator. Edit Catalog.kt and run mise run generate:units.
package org.maplibre.spatialk.units

import kotlin.jvm.JvmField

/** Gold Coast surveying units used in legacy Ghanaian coordinate systems. */
public data object Ghana {
    /**
     * Definition: Gold Coast foot, EPSG 9094.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val GoldCoastFeet: LengthUnit = LengthUnit(0.3047997101815088, "ft")
}
