// Generated by tools/units-generator. Edit Catalog.kt and run mise run generate:units.
package org.maplibre.spatialk.units

import kotlin.jvm.JvmField

/** Indian historical survey definitions from EPSG. */
public data object India {
    /**
     * Definition: Indian foot, EPSG 9080.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val SurveyFeet: LengthUnit = LengthUnit(0.30479951024814694, "ft")

    /**
     * Definition: Indian yard, EPSG 9084.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val SurveyYards: LengthUnit = LengthUnit(0.9143985307444408, "yd")

    /**
     * Definition: Indian foot (1937), EPSG 9081.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val SurveyFeet1937: LengthUnit = LengthUnit(0.30479841, "ft")

    /**
     * Definition: Indian yard (1937), EPSG 9085.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val SurveyYards1937: LengthUnit = LengthUnit(0.91439523, "yd")

    /**
     * Definition: Indian foot (1962), EPSG 9082.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val SurveyFeet1962: LengthUnit = LengthUnit(0.3047996, "ft")

    /**
     * Definition: Indian yard (1962), EPSG 9086.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val SurveyYards1962: LengthUnit = LengthUnit(0.9143988, "yd")

    /**
     * Definition: Indian foot (1975), EPSG 9083.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val SurveyFeet1975: LengthUnit = LengthUnit(0.3047995, "ft")

    /**
     * Definition: Indian yard (1975), EPSG 9087.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val SurveyYards1975: LengthUnit = LengthUnit(0.9143985, "yd")

    /**
     * Assam land areas. Foot-based counts use the ordinary foot (0.3048 meters), documented in the
     * [1976 conversion schedule](https://www.py.gov.in/sites/default/files/revenuemanual3part1acts.pdf).
     */
    public data object Assam {
        /**
         * Definition: 1 Assam bigha = 14400 international square feet = 5 katha.
         *
         * See
         * [Assam Resettlement Policy Framework (2022), section 7.2](https://igr.assam.gov.in/sites/default/files/swf_utility_folder/departments/asdma_revenue_uneecopscloud_com_oid_70/menu/document/airbmp_rpf_0.pdf).
         */
        @JvmField public val Bigha: AreaUnit = AreaUnit(1_337.8037760000002, "bigha")

        /**
         * Definition: 1 Assam katha = 2880 international square feet = 20 lecha.
         *
         * See
         * [Assam Resettlement Policy Framework (2022), section 7.2](https://igr.assam.gov.in/sites/default/files/swf_utility_folder/departments/asdma_revenue_uneecopscloud_com_oid_70/menu/document/airbmp_rpf_0.pdf).
         */
        @JvmField public val Katha: AreaUnit = AreaUnit(267.5607552, "katha")

        /**
         * Definition: 1 Assam lecha = 144 international square feet.
         *
         * See
         * [Assam Resettlement Policy Framework (2022), section 7.2](https://igr.assam.gov.in/sites/default/files/swf_utility_folder/departments/asdma_revenue_uneecopscloud_com_oid_70/menu/document/airbmp_rpf_0.pdf).
         */
        @JvmField public val Lecha: AreaUnit = AreaUnit(13.378037760000002, "lecha")
    }
}
