// Generated by tools/units-generator. Edit Catalog.kt and run mise run generate:units.
package org.maplibre.spatialk.units

import kotlin.jvm.JvmField
import org.maplibre.spatialk.units.Metric.SquareCentimeters
import org.maplibre.spatialk.units.Metric.SquareDecameters
import org.maplibre.spatialk.units.Metric.SquareDecimeters
import org.maplibre.spatialk.units.Metric.SquareHectometers
import org.maplibre.spatialk.units.Metric.SquareKilometers
import org.maplibre.spatialk.units.Metric.SquareMeters
import org.maplibre.spatialk.units.Metric.SquareMillimeters

/** Metric lengths and land areas. */
public data object Metric {
    /**
     * Definition: 1 mm² = 0.000001 square meters.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField public val SquareMillimeters: AreaUnit = AreaUnit(0.000001, "mm²")

    /**
     * Definition: 1 cm² = 0.0001 square meters.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField public val SquareCentimeters: AreaUnit = AreaUnit(0.0001, "cm²")

    /**
     * Definition: 1 m² = 1.0 square meters.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField public val SquareMeters: AreaUnit = AreaUnit(1.0, "m²")

    /**
     * Definition: 1 km² = 1000000.0 square meters.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField public val SquareKilometers: AreaUnit = AreaUnit(1_000_000.0, "km²")

    /**
     * Definition: 1 ca = 1.0 square meters.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField public val Centiares: AreaUnit = AreaUnit(1.0, "ca")

    /**
     * Definition: 1 da = 10.0 square meters.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField public val Deciares: AreaUnit = AreaUnit(10.0, "da")

    /**
     * Definition: 1 a = 100.0 square meters.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField public val Ares: AreaUnit = AreaUnit(100.0, "a")

    /**
     * Definition: 1 daa = 1000.0 square meters.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField public val Decares: AreaUnit = AreaUnit(1_000.0, "daa")

    /**
     * Definition: 1 ha = 10000.0 square meters.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField public val Hectares: AreaUnit = AreaUnit(10_000.0, "ha")

    /**
     * Definition: 1 dm² = 0.01 square meters.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField public val SquareDecimeters: AreaUnit = AreaUnit(0.01, "dm²")

    /**
     * Definition: 1 dam² = 100.0 square meters.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField public val SquareDecameters: AreaUnit = AreaUnit(100.0, "dam²")

    /**
     * Definition: 1 hm² = 10000.0 square meters.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField public val SquareHectometers: AreaUnit = AreaUnit(10_000.0, "hm²")

    /**
     * Definition: 1 mm = 0.001 meters.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField
    public val Millimeters: LengthUnit = LengthUnit(0.001, "mm", squaredUnit = SquareMillimeters)

    /**
     * Definition: 1 cm = 0.01 meters.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField
    public val Centimeters: LengthUnit = LengthUnit(0.01, "cm", squaredUnit = SquareCentimeters)

    /**
     * Definition: 1 m = 1.0 meters.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField public val Meters: LengthUnit = LengthUnit(1.0, "m", squaredUnit = SquareMeters)

    /**
     * Definition: 1 km = 1000.0 meters.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField
    public val Kilometers: LengthUnit = LengthUnit(1_000.0, "km", squaredUnit = SquareKilometers)

    /**
     * Definition: 1 dm = 0.1 meters.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField
    public val Decimeters: LengthUnit = LengthUnit(0.1, "dm", squaredUnit = SquareDecimeters)

    /**
     * Definition: 1 dam = 10.0 meters.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField
    public val Decameters: LengthUnit = LengthUnit(10.0, "dam", squaredUnit = SquareDecameters)

    /**
     * Definition: 1 hm = 100.0 meters.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField
    public val Hectometers: LengthUnit = LengthUnit(100.0, "hm", squaredUnit = SquareHectometers)
}
