// Generated by tools/units-generator. Edit Catalog.kt and run mise run generate:units.
package org.maplibre.spatialk.units

import kotlin.jvm.JvmField

/** International nautical lengths. */
public data object Nautical {
    /**
     * Definition: 1 fathom = 6 international feet.
     *
     * See [NIST Handbook 44](https://www.nist.gov/document/2026-nist-handbook-44-appendix-c).
     */
    @JvmField public val Fathoms: LengthUnit = LengthUnit(1.8288, "fathom")

    /**
     * Definition: 1 international cable = 1/10 international nautical mile.
     *
     * See
     * [Official international cable definition](https://www.itlos.org/fileadmin/itlos/documents/cases/case_no_2/merits/E0320AM.pdf).
     */
    @JvmField public val InternationalCables: LengthUnit = LengthUnit(185.2, "cable")

    /**
     * Definition: 1 nmi = 1852.0 meters.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField public val NauticalMiles: LengthUnit = LengthUnit(1_852.0, "nmi")
}
