// Generated by tools/units-generator. Edit Catalog.kt and run mise run generate:units.
package org.maplibre.spatialk.units

import kotlin.jvm.JvmField

/** Nepali land measures, qualified by region. */
public data object Nepal {
    /**
     * Hill-region land areas, defined by the textbook's foot counts and subdivision ratios using
     * its stated 0.3048-meter foot.
     */
    public data object Hill {
        /**
         * Definition: 1 ropani = 5476 international square feet = 16 aana.
         *
         * See
         * [Nepal CDC Mathematics Grade 9 (2022), page 116](https://lib.moecdc.gov.np/catalog/opac_css/index.php?id=13786&lvl=notice_display).
         */
        @JvmField public val Ropani: AreaUnit = AreaUnit(508.73704704000005, "ropani")

        /**
         * Definition: 1 aana = 1/16 ropani = 4 paisa.
         *
         * See
         * [Nepal CDC Mathematics Grade 9 (2022), page 116](https://lib.moecdc.gov.np/catalog/opac_css/index.php?id=13786&lvl=notice_display).
         */
        @JvmField public val Aana: AreaUnit = AreaUnit(31.796065440000003, "aana")

        /**
         * Definition: 1 paisa = 1/64 ropani = 4 daam.
         *
         * See
         * [Nepal CDC Mathematics Grade 9 (2022), page 116](https://lib.moecdc.gov.np/catalog/opac_css/index.php?id=13786&lvl=notice_display).
         */
        @JvmField public val Paisa: AreaUnit = AreaUnit(7.949016360000001, "paisa")

        /**
         * Definition: 1 daam = 1/256 ropani.
         *
         * See
         * [Nepal CDC Mathematics Grade 9 (2022), page 116](https://lib.moecdc.gov.np/catalog/opac_css/index.php?id=13786&lvl=notice_display).
         */
        @JvmField public val Daam: AreaUnit = AreaUnit(1.9872540900000002, "daam")
    }

    /** Terai-region land areas. A bigha is 20 kattha, each of 20 dhur. */
    public data object Terai {
        /**
         * Definition: 1 Terai bigha = 72900 international square feet = 20 kattha.
         *
         * See
         * [Nepal CDC Mathematics Grade 9 (2022), page 116](https://lib.moecdc.gov.np/catalog/opac_css/index.php?id=13786&lvl=notice_display).
         */
        @JvmField public val Bigha: AreaUnit = AreaUnit(6_772.631616000001, "bigha")

        /**
         * Definition: 1 Terai kattha = 3645 international square feet = 20 dhur.
         *
         * See
         * [Nepal CDC Mathematics Grade 9 (2022), page 116](https://lib.moecdc.gov.np/catalog/opac_css/index.php?id=13786&lvl=notice_display).
         */
        @JvmField public val Kattha: AreaUnit = AreaUnit(338.6315808, "kattha")

        /**
         * Definition: 1 Terai dhur = 182.25 international square feet.
         *
         * See
         * [Nepal CDC Mathematics Grade 9 (2022), page 116](https://lib.moecdc.gov.np/catalog/opac_css/index.php?id=13786&lvl=notice_display).
         */
        @JvmField public val Dhur: AreaUnit = AreaUnit(16.931579040000003, "dhur")
    }
}
