// Generated by tools/units-generator. Edit Catalog.kt and run mise run generate:units.
package org.maplibre.spatialk.units

import kotlin.jvm.JvmField

/** British historical surveying and nautical definitions. */
public data object UK {
    /**
     * Definition: Clarke foot, EPSG 9005: 0.3047972654 meters.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val ClarkeFeet: LengthUnit = LengthUnit(0.3047972654, "ft")

    /**
     * Definition: Clarke yard, EPSG 9037: 0.9143917962 meters.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val ClarkeYards: LengthUnit = LengthUnit(0.9143917962, "yd")

    /**
     * Definition: Clarke chain, EPSG 9038: 20.1166195164 meters.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val ClarkeChains: LengthUnit = LengthUnit(20.1166195164, "ch")

    /**
     * Definition: Clarke link, EPSG 9039: 0.201166195164 meters.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val ClarkeLinks: LengthUnit = LengthUnit(0.201166195164, "link")

    /**
     * Definition: British foot (Sears 1922), EPSG 9041.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Sears1922Feet: LengthUnit = LengthUnit(0.3047994715386762, "ft")

    /**
     * Definition: British yard (Sears 1922), EPSG 9040.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Sears1922Yards: LengthUnit = LengthUnit(0.9143984146160287, "yd")

    /**
     * Definition: British chain (Sears 1922), EPSG 9042.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Sears1922Chains: LengthUnit = LengthUnit(20.116765121552632, "ch")

    /**
     * Definition: British link (Sears 1922), EPSG 9043.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Sears1922Links: LengthUnit = LengthUnit(0.2011676512155263, "link")

    /**
     * Definition: British foot (Sears 1922 truncated), EPSG 9300.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Sears1922TruncatedFeet: LengthUnit = LengthUnit(0.30479933333333337, "ft")

    /**
     * Definition: British yard (Sears 1922 truncated), EPSG 9099.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Sears1922TruncatedYards: LengthUnit = LengthUnit(0.914398, "yd")

    /**
     * Definition: British chain (Sears 1922 truncated), EPSG 9301.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Sears1922TruncatedChains: LengthUnit = LengthUnit(20.116756, "ch")

    /**
     * Definition: British link (Sears 1922 truncated), EPSG 9302.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Sears1922TruncatedLinks: LengthUnit = LengthUnit(0.20116756, "link")

    /**
     * Definition: British foot (Benoit 1895 A), EPSG 9051.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Benoit1895AFeet: LengthUnit = LengthUnit(0.3047997333333333, "ft")

    /**
     * Definition: British yard (Benoit 1895 A), EPSG 9050.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Benoit1895AYards: LengthUnit = LengthUnit(0.9143992, "yd")

    /**
     * Definition: British chain (Benoit 1895 A), EPSG 9052.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Benoit1895AChains: LengthUnit = LengthUnit(20.1167824, "ch")

    /**
     * Definition: British link (Benoit 1895 A), EPSG 9053.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Benoit1895ALinks: LengthUnit = LengthUnit(0.201167824, "link")

    /**
     * Definition: British foot (Benoit 1895 B), EPSG 9061.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Benoit1895BFeet: LengthUnit = LengthUnit(0.30479973476327077, "ft")

    /**
     * Definition: British yard (Benoit 1895 B), EPSG 9060.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Benoit1895BYards: LengthUnit = LengthUnit(0.9143992042898124, "yd")

    /**
     * Definition: British chain (Benoit 1895 B), EPSG 9062.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Benoit1895BChains: LengthUnit = LengthUnit(20.116782494375872, "ch")

    /**
     * Definition: British link (Benoit 1895 B), EPSG 9063.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Benoit1895BLinks: LengthUnit = LengthUnit(0.2011678249437587, "link")

    /**
     * Definition: British foot (1865), EPSG 9070.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Feet1865: LengthUnit = LengthUnit(0.30480083333333335, "ft")

    /**
     * Definition: British foot (1936), EPSG 9095.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Feet1936: LengthUnit = LengthUnit(0.3048007491, "ft")

    /**
     * Definition: 1 Admiralty nautical mile = 6080 international feet.
     *
     * See
     * [IHO Hydrographic Dictionary, cable](https://portal.iho.int/iho-ohi/S32/engView.php?page=30).
     */
    @JvmField public val AdmiraltyNauticalMiles: LengthUnit = LengthUnit(1_853.1840000000002, "nmi")

    /**
     * Definition: 1 Admiralty cable = 608 international feet.
     *
     * See
     * [IHO Hydrographic Dictionary, cable](https://portal.iho.int/iho-ohi/S32/engView.php?page=30).
     */
    @JvmField public val AdmiraltyCables: LengthUnit = LengthUnit(185.3184, "cable")
}
