// Generated by tools/units-generator. Edit Catalog.kt and run mise run generate:units.
package org.maplibre.spatialk.units

import kotlin.jvm.JvmField

/**
 * Common units for terrestrial mapping. Each property aliases a definition in a specialist catalog.
 */
public data object Units {
    /** The same unit as [Metric.SquareMeters]. */
    @JvmField public val SquareMeters: AreaUnit = Metric.SquareMeters

    /** The same unit as [Metric.SquareKilometers]. */
    @JvmField public val SquareKilometers: AreaUnit = Metric.SquareKilometers

    /** The same unit as [Metric.Millimeters]. */
    @JvmField public val Millimeters: LengthUnit = Metric.Millimeters

    /** The same unit as [Metric.Centimeters]. */
    @JvmField public val Centimeters: LengthUnit = Metric.Centimeters

    /** The same unit as [Metric.Meters]. */
    @JvmField public val Meters: LengthUnit = Metric.Meters

    /** The same unit as [Metric.Kilometers]. */
    @JvmField public val Kilometers: LengthUnit = Metric.Kilometers

    /** The same unit as [Metric.Hectares]. */
    @JvmField public val Hectares: AreaUnit = Metric.Hectares

    /** The same unit as [Customary.SquareFeet]. */
    @JvmField public val SquareFeet: AreaUnit = Customary.SquareFeet

    /** The same unit as [Customary.SquareYards]. */
    @JvmField public val SquareYards: AreaUnit = Customary.SquareYards

    /** The same unit as [Customary.SquareMiles]. */
    @JvmField public val SquareMiles: AreaUnit = Customary.SquareMiles

    /** The same unit as [Customary.Acres]. */
    @JvmField public val Acres: AreaUnit = Customary.Acres

    /** The same unit as [Customary.Inches]. */
    @JvmField public val Inches: LengthUnit = Customary.Inches

    /** The same unit as [Customary.Feet]. */
    @JvmField public val Feet: LengthUnit = Customary.Feet

    /** The same unit as [Customary.Yards]. */
    @JvmField public val Yards: LengthUnit = Customary.Yards

    /** The same unit as [Customary.LandMiles]. */
    @JvmField public val Miles: LengthUnit = Customary.LandMiles

    /** The same unit as [Angles.Radians]. */
    @JvmField public val Radians: RotationUnit = Angles.Radians

    /** The same unit as [Angles.Degrees]. */
    @JvmField public val Degrees: RotationUnit = Angles.Degrees

    /** The same unit as [Angles.Turns]. */
    @JvmField public val Turns: RotationUnit = Angles.Turns

    /** The same unit as [Angles.ArcMinutes]. */
    @JvmField public val ArcMinutes: RotationUnit = Angles.ArcMinutes

    /** The same unit as [Angles.ArcSeconds]. */
    @JvmField public val ArcSeconds: RotationUnit = Angles.ArcSeconds

    /** The same unit as [Nautical.NauticalMiles]. */
    @JvmField public val NauticalMiles: LengthUnit = Nautical.NauticalMiles
}
