package org.maplibre.spatialk.codegen

import com.facebook.ktfmt.format.Formatter
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import java.io.File
import org.maplibre.spatialk.codegen.catalog.catalog

private const val PACKAGE = "org.maplibre.spatialk.units"
private const val CATALOG = "$PACKAGE.catalog"
private const val EXTENSIONS = "$PACKAGE.extensions"
private const val HEADER =
    "Generated by tools/units-generator. Edit catalog files in tools/units-generator and run mise run generate:units."

private val units = catalog.flatMap { it.units }

fun main(args: Array<String>) {
    val root = File(args[0])
    val files =
        catalog
            .filter { '.' !in it.name }
            .map { family ->
                kotlinFile(family.name, CATALOG).addType(catalogObject(family)).build()
            } +
            listOf(
                kotlinFile("Units").addType(commonUnits()).build(),
                conversionHelpers(),
            )
    for (file in files) {
        val path =
            "units/src/commonMain/kotlin/${file.packageName.replace('.', '/')}/${file.name}.kt"
        val target = root.resolve(path)
        val content = Formatter.format(Formatter.KOTLINLANG_FORMAT, file.toString())
        if ("--check" in args) {
            check(target.readText() == content) {
                "$path is out of date. Run mise run generate:units."
            }
        } else {
            target.parentFile.mkdirs()
            target.writeText(content)
        }
    }
}

private fun kotlinFile(name: String, packageName: String = PACKAGE): FileSpec.Builder =
    FileSpec.builder(packageName, name).addFileComment("%L", HEADER)

private fun conversionHelpers(): FileSpec {
    val helpers =
        kotlinFile("unitConversions", EXTENSIONS)
            .addAnnotation(
                AnnotationSpec.builder(ClassName("kotlin.jvm", "JvmSynthetic"))
                    .useSiteTarget(AnnotationSpec.UseSiteTarget.FILE)
                    .build()
            )
    for (unit in units) {
        val helper = unit.helper ?: continue
        for (receiver in listOf("Double", "Int")) {
            helpers.addProperty(
                PropertySpec.builder(helper, unit.dimension.quantityType, KModifier.PUBLIC)
                    .receiver(ClassName("kotlin", receiver))
                    .inlineGetter(
                        "%L%M(%M)",
                        if (receiver == "Int") "toDouble()." else "",
                        MemberName(EXTENSIONS, "to${unit.dimension.quantity}"),
                        unit.member,
                    )
                    .addKdoc(
                        "Creates a [%T] from a scalar value in [%T.%L].\n",
                        unit.dimension.quantityType,
                        catalogClass(unit.family),
                        unit.name,
                    )
                    .build()
            )
        }
        helpers.addProperty(
            PropertySpec.builder(
                    "in${unit.commonName}",
                    ClassName("kotlin", "Double"),
                    KModifier.PUBLIC,
                )
                .receiver(unit.dimension.quantityType)
                .inlineGetter("toDouble(%M)", unit.member)
                .addKdoc(
                    "Returns this [%T] as a scalar value in [%T.%L].\n",
                    unit.dimension.quantityType,
                    catalogClass(unit.family),
                    unit.name,
                )
                .build()
        )
    }
    return helpers.build()
}

private fun catalogObject(family: Family): TypeSpec {
    val type =
        TypeSpec.objectBuilder(family.name.substringAfterLast('.'))
            .addModifiers(KModifier.PUBLIC, KModifier.DATA)
            .addKdoc("%L\n", family.description)
    // Area fields must be ready before length fields refer to them.
    val definitions = family.units.sortedBy { it.dimension != Dimension.AREA }
    for (unit in definitions) {
        val property =
            PropertySpec.builder(unit.name, unit.dimension.unitType, KModifier.PUBLIC)
                .addAnnotation(ClassName("kotlin.jvm", "JvmField"))
                .addKdoc(
                    "Definition: %L.\n\nSee [%L](%L).\n",
                    unit.definition,
                    unit.source.title,
                    unit.source.url,
                )
        val initializer =
            CodeBlock.builder().add("%T(%L, %S", unit.dimension.unitType, unit.factor, unit.symbol)
        unit.squaredUnit?.let {
            initializer.add(", squaredUnit = %M", MemberName(catalogClass(family.name), it))
        }
        type.addProperty(property.initializer(initializer.add(")").build()).build())
    }
    for (child in catalog.filter { it.name.substringBeforeLast('.', "") == family.name }) {
        type.addType(catalogObject(child))
    }
    return type.build()
}

private fun commonUnits(): TypeSpec {
    val type =
        TypeSpec.objectBuilder("Units")
            .addModifiers(KModifier.PUBLIC, KModifier.DATA)
            .addKdoc(
                "Common units for terrestrial mapping. Each property aliases a definition in a specialist catalog.\n"
            )
    for (unit in units) {
        val commonName = unit.commonName ?: continue
        type.addProperty(
            PropertySpec.builder(
                    commonName,
                    unit.dimension.unitType,
                    KModifier.PUBLIC,
                )
                .addAnnotation(ClassName("kotlin.jvm", "JvmField"))
                .addKdoc(
                    "The same unit as [%T.%L].\n",
                    catalogClass(unit.family),
                    unit.name,
                )
                .initializer("%T.%L", catalogClass(unit.family), unit.name)
                .build()
        )
    }
    return type.build()
}

private fun PropertySpec.Builder.inlineGetter(
    format: String,
    vararg args: Any,
): PropertySpec.Builder =
    getter(
        FunSpec.getterBuilder()
            .addModifiers(KModifier.INLINE)
            .addStatement("return $format", *args)
            .build()
    )
