// Generated by tools/units-generator. Edit catalog files in tools/units-generator and run mise run
// generate:units.
package org.maplibre.spatialk.units.catalog

import kotlin.jvm.JvmField
import kotlin.math.PI
import org.maplibre.spatialk.units.RotationUnit

/** Angular units. Degrees, arcminutes, and arcseconds can also be formatted as DMS. */
public data object Angles {
    /**
     * Definition: 1 radian = 180/π degrees.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField public val Radians: RotationUnit = RotationUnit(180.0 / PI, "rad")

    /**
     * Definition: 1 gradian = 0.9 degree; a full turn is 400 gradians.
     *
     * See
     * [EU units directive](https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX:01980L0181-20200613).
     */
    @JvmField public val Gradians: RotationUnit = RotationUnit(0.9, "gon")

    /**
     * Definition: 1 ° = 1.0 degrees.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField public val Degrees: RotationUnit = RotationUnit(1.0, "°")

    /**
     * Definition: 1 turn = 360 degrees (one revolution).
     *
     * See
     * [EU units directive](https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX:01980L0181-20200613).
     */
    @JvmField public val Turns: RotationUnit = RotationUnit(360.0, "turn")

    /**
     * Definition: 1 milliradian = 1/1000 radian.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField public val Milliradians: RotationUnit = RotationUnit(0.001 * 180.0 / PI, "mrad")

    /**
     * Definition: 1 microradian = 1/1000000 radian (EPSG 9109).
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Microradians: RotationUnit = RotationUnit(0.000001 * 180.0 / PI, "µrad")

    /**
     * Definition: 1 milliarcsecond = 1/1000 arcsecond (EPSG 1031).
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val MilliarcSeconds: RotationUnit = RotationUnit(1.0 / 3600000, "mas")

    /**
     * Definition: 1 centesimal minute = 1/100 gradian (EPSG 9112).
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val CentesimalMinutes: RotationUnit = RotationUnit(0.9 / 100, "cgon")

    /**
     * Definition: 1 centesimal second = 1/10000 gradian (EPSG 9113).
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val CentesimalSeconds: RotationUnit = RotationUnit(0.9 / 10000, "cc")

    /**
     * Definition: 1 mil = 1/6400 turn.
     *
     * See
     * [Brunton OmniSight specification](https://conibe.com/images/archivos/Brunton-Omnisight-ss.pdf).
     */
    @JvmField public val Mils6400: RotationUnit = RotationUnit(360.0 / 6400, "mil")

    /**
     * Definition: 1 angular hour = 15 degrees.
     *
     * See [NOAA solar-position calculations](https://gml.noaa.gov/grad/solcalc/solareqns.PDF).
     */
    @JvmField public val AngularHours: RotationUnit = RotationUnit(15.0, "h")

    /**
     * Definition: 1 angular minute = 1/60 angular hour.
     *
     * See [NOAA solar-position calculations](https://gml.noaa.gov/grad/solcalc/solareqns.PDF).
     */
    @JvmField public val AngularMinutes: RotationUnit = RotationUnit(15.0 / 60, "min")

    /**
     * Definition: 1 angular second = 1/3600 angular hour.
     *
     * See [NOAA solar-position calculations](https://gml.noaa.gov/grad/solcalc/solareqns.PDF).
     */
    @JvmField public val AngularSeconds: RotationUnit = RotationUnit(15.0 / 3600, "s")

    /**
     * Definition: 1 arcminute = 1/60 degree.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField public val ArcMinutes: RotationUnit = RotationUnit(1.0 / 60, "′")

    /**
     * Definition: 1 arcsecond = 1/3600 degree.
     *
     * See [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf).
     */
    @JvmField public val ArcSeconds: RotationUnit = RotationUnit(1.0 / 60 / 60, "″")
}
