// Generated by tools/units-generator. Edit catalog files in tools/units-generator and run mise run
// generate:units.
package org.maplibre.spatialk.units.catalog

import kotlin.jvm.JvmField
import org.maplibre.spatialk.units.AreaUnit
import org.maplibre.spatialk.units.LengthUnit
import org.maplibre.spatialk.units.catalog.Customary.SquareFeet
import org.maplibre.spatialk.units.catalog.Customary.SquareInches
import org.maplibre.spatialk.units.catalog.Customary.SquareMiles
import org.maplibre.spatialk.units.catalog.Customary.SquareRods
import org.maplibre.spatialk.units.catalog.Customary.SquareYards

/** Land lengths and areas based on the international foot (exactly 0.3048 meters). */
public data object Customary {
    /**
     * Definition: 1 in² = 0.00064516 square meters.
     *
     * See [NIST Handbook 44](https://www.nist.gov/document/2026-nist-handbook-44-appendix-c).
     */
    @JvmField public val SquareInches: AreaUnit = AreaUnit(0.00064516, "in²")

    /**
     * Definition: 1 ft² = 0.09290304 square meters.
     *
     * See [NIST Handbook 44](https://www.nist.gov/document/2026-nist-handbook-44-appendix-c).
     */
    @JvmField public val SquareFeet: AreaUnit = AreaUnit(0.09290304, "ft²")

    /**
     * Definition: 1 yd² = 0.83612736 square meters.
     *
     * See [NIST Handbook 44](https://www.nist.gov/document/2026-nist-handbook-44-appendix-c).
     */
    @JvmField public val SquareYards: AreaUnit = AreaUnit(0.83612736, "yd²")

    /**
     * Definition: 1 mi² = 2589988.110336 square meters.
     *
     * See [NIST Handbook 44](https://www.nist.gov/document/2026-nist-handbook-44-appendix-c).
     */
    @JvmField public val SquareMiles: AreaUnit = AreaUnit(2_589_988.110336, "mi²")

    /**
     * Definition: 1 rd² = 25.29285264 square meters.
     *
     * See [NIST Handbook 44](https://www.nist.gov/document/2026-nist-handbook-44-appendix-c).
     */
    @JvmField public val SquareRods: AreaUnit = AreaUnit(25.29285264, "rd²")

    /**
     * Definition: 1 acre = 43560 international square feet.
     *
     * See [NIST Handbook 44](https://www.nist.gov/document/2026-nist-handbook-44-appendix-c).
     */
    @JvmField public val Acres: AreaUnit = AreaUnit(4_046.8564224, "acre")

    /**
     * Definition: 1 in = 0.0254 meters.
     *
     * See [NIST Handbook 44](https://www.nist.gov/document/2026-nist-handbook-44-appendix-c).
     */
    @JvmField public val Inches: LengthUnit = LengthUnit(0.0254, "in", squaredUnit = SquareInches)

    /**
     * Definition: 1 ft = 0.3048 meters.
     *
     * See [NIST Handbook 44](https://www.nist.gov/document/2026-nist-handbook-44-appendix-c).
     */
    @JvmField public val Feet: LengthUnit = LengthUnit(0.3048, "ft", squaredUnit = SquareFeet)

    /**
     * Definition: 1 yd = 0.9144 meters.
     *
     * See [NIST Handbook 44](https://www.nist.gov/document/2026-nist-handbook-44-appendix-c).
     */
    @JvmField public val Yards: LengthUnit = LengthUnit(0.9144, "yd", squaredUnit = SquareYards)

    /**
     * Definition: 1 mi = 1609.344 meters.
     *
     * See [NIST Handbook 44](https://www.nist.gov/document/2026-nist-handbook-44-appendix-c).
     */
    @JvmField
    public val LandMiles: LengthUnit = LengthUnit(1_609.344, "mi", squaredUnit = SquareMiles)

    /**
     * Definition: 1 Gunter link = 0.66 international feet.
     *
     * See [NIST Handbook 44](https://www.nist.gov/document/2026-nist-handbook-44-appendix-c).
     */
    @JvmField public val GunterLinks: LengthUnit = LengthUnit(0.201168, "link")

    /**
     * Definition: 1 rod = 16.5 international feet; also called a pole or perch.
     *
     * See [NIST Handbook 44](https://www.nist.gov/document/2026-nist-handbook-44-appendix-c).
     */
    @JvmField public val Rods: LengthUnit = LengthUnit(5.0292, "rod", squaredUnit = SquareRods)

    /**
     * Definition: 1 Gunter chain = 66 international feet.
     *
     * See [NIST Handbook 44](https://www.nist.gov/document/2026-nist-handbook-44-appendix-c).
     */
    @JvmField public val GunterChains: LengthUnit = LengthUnit(20.1168, "ch")

    /**
     * Definition: 1 furlong = 660 international feet.
     *
     * See [NIST Handbook 44](https://www.nist.gov/document/2026-nist-handbook-44-appendix-c).
     */
    @JvmField public val Furlongs: LengthUnit = LengthUnit(201.168, "fur")

    /**
     * Definition: 1 land league = 3 international-foot miles.
     *
     * See [NIST Handbook 44](https://www.nist.gov/document/2026-nist-handbook-44-appendix-c).
     */
    @JvmField public val LandLeagues: LengthUnit = LengthUnit(4_828.032, "lea")
}
