// Generated by tools/units-generator. Edit catalog files in tools/units-generator and run mise run
// generate:units.
package org.maplibre.spatialk.units.catalog

import kotlin.jvm.JvmField
import org.maplibre.spatialk.units.RotationUnit

/** Finnish angular divisions, with 6000 piiru per turn. */
public data object Finland {
    /**
     * Definition: 1 piiru = 1/6000 turn.
     *
     * See
     * [Finnish Roads and Waterways Administration SI guide (1975), page 52](https://www.doria.fi/bitstream/10024/132346/1/tie755.pdf).
     */
    @JvmField public val Mils6000: RotationUnit = RotationUnit(360.0 / 6000, "piiru")
}
