// Generated by tools/units-generator. Edit catalog files in tools/units-generator and run mise run
// generate:units.
package org.maplibre.spatialk.units.catalog

import kotlin.jvm.JvmField
import org.maplibre.spatialk.units.LengthUnit

/**
 * Surveying units used in Malaysian mapping: full Sears definitions in East Malaysia; truncated
 * Sears and Benoit definitions in West Malaysia. See
 * [JUPEM (2009)](https://www.jupem.gov.my/jupem18a/assets/uploads/files/pekeliling/38724-pek-1-2009.pdf)
 * and [IHO Revised Kertau](https://registry.iho.int/fdd/view5.do?idx=2334&type=5&valueType=0).
 */
public data object Malaysia {
    /**
     * Definition: British foot (Sears 1922), EPSG 9041.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Sears1922Feet: LengthUnit = LengthUnit(0.3047994715386762, "ft")

    /**
     * Definition: British yard (Sears 1922), EPSG 9040.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Sears1922Yards: LengthUnit = LengthUnit(0.9143984146160287, "yd")

    /**
     * Definition: British chain (Sears 1922), EPSG 9042.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Sears1922Chains: LengthUnit = LengthUnit(20.116765121552632, "ch")

    /**
     * Definition: British link (Sears 1922), EPSG 9043.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Sears1922Links: LengthUnit = LengthUnit(0.2011676512155263, "link")

    /**
     * Definition: British foot (Sears 1922 truncated), EPSG 9300.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Sears1922TruncatedFeet: LengthUnit = LengthUnit(0.30479933333333337, "ft")

    /**
     * Definition: British yard (Sears 1922 truncated), EPSG 9099.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Sears1922TruncatedYards: LengthUnit = LengthUnit(0.914398, "yd")

    /**
     * Definition: British chain (Sears 1922 truncated), EPSG 9301.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Sears1922TruncatedChains: LengthUnit = LengthUnit(20.116756, "ch")

    /**
     * Definition: British link (Sears 1922 truncated), EPSG 9302.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Sears1922TruncatedLinks: LengthUnit = LengthUnit(0.20116756, "link")

    /**
     * Definition: British foot (Benoit 1895 B), EPSG 9061.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Benoit1895BFeet: LengthUnit = LengthUnit(0.30479973476327077, "ft")

    /**
     * Definition: British yard (Benoit 1895 B), EPSG 9060.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Benoit1895BYards: LengthUnit = LengthUnit(0.9143992042898124, "yd")

    /**
     * Definition: British chain (Benoit 1895 B), EPSG 9062.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Benoit1895BChains: LengthUnit = LengthUnit(20.116782494375872, "ch")

    /**
     * Definition: British link (Benoit 1895 B), EPSG 9063.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val Benoit1895BLinks: LengthUnit = LengthUnit(0.2011678249437587, "link")
}
