// Generated by tools/units-generator. Edit catalog files in tools/units-generator and run mise run
// generate:units.
package org.maplibre.spatialk.units.catalog

import kotlin.jvm.JvmField
import org.maplibre.spatialk.units.LengthUnit

/**
 * German legal meters used in Namibia's Schwarzeck coordinate systems. See the
 * [Roads Authority Survey Manual (2014), section 1.2](https://www.ra.org.na/cms/Lists/Downloads/Attachments/19/SURVEY%20MANUAL_oct_%202014.pdf).
 */
public data object Namibia {
    /**
     * Definition: German legal meter, EPSG 9031: 1.0000135965 SI meters.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val GermanLegalMeters: LengthUnit = LengthUnit(1.0000135965, "m")
}
