// Generated by tools/units-generator. Edit catalog files in tools/units-generator and run mise run
// generate:units.
package org.maplibre.spatialk.units.catalog

import kotlin.jvm.JvmField
import org.maplibre.spatialk.units.LengthUnit

/**
 * Surveying definitions shared across countries. The Indian 1937 definition is used from Bangladesh
 * to Vietnam; the British 1936 foot is used in British and Irish metric conversions. See
 * [BGS unit usage](https://webapps.bgs.ac.uk/data/vocabularies/viewdata.cfm?name=DIC_UNIT_OF_MEASURE&row=21).
 */
public data object Survey {
    /**
     * Definition: Indian foot (1937), EPSG 9081.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val IndianFeet1937: LengthUnit = LengthUnit(0.30479841, "ft")

    /**
     * Definition: Indian yard (1937), EPSG 9085.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val IndianYards1937: LengthUnit = LengthUnit(0.91439523, "yd")

    /**
     * Definition: British foot (1936), EPSG 9095.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val BritishFeet1936: LengthUnit = LengthUnit(0.3048007491, "ft")
}
