// Generated by tools/units-generator. Edit catalog files in tools/units-generator and run mise run
// generate:units.
package org.maplibre.spatialk.units.catalog

import kotlin.jvm.JvmField
import org.maplibre.spatialk.units.RotationUnit

/** Historical Swedish angular divisions, with 6300 streck per turn. */
public data object Sweden {
    /**
     * Definition: 1 historical streck = 1/6300 turn.
     *
     * See
     * [Finnish Roads and Waterways Administration SI guide (1975), page 52](https://www.doria.fi/bitstream/10024/132346/1/tie755.pdf).
     */
    @JvmField public val Streck6300: RotationUnit = RotationUnit(360.0 / 6300, "streck")
}
