// Generated by tools/units-generator. Edit catalog files in tools/units-generator and run mise run
// generate:units.
package org.maplibre.spatialk.units.catalog

import kotlin.jvm.JvmField
import org.maplibre.spatialk.units.AreaUnit
import org.maplibre.spatialk.units.LengthUnit
import org.maplibre.spatialk.units.catalog.Thailand.SquareWa

/**
 * Thai land measures: rai, ngan, square wa, and wa. See
 * [Treasury Department notation](https://www.treasury.go.th/en/services/land-assessment/search-land-price).
 */
public data object Thailand {
    /**
     * Definition: 1 square wa = 4 square meters.
     *
     * See
     * [Thai Agricultural Land Reform Office](https://alro.go.th/uploads/org/mukdahan/download/article/article_20190822204852.pdf).
     */
    @JvmField public val SquareWa: AreaUnit = AreaUnit(4.0, "ตร.วา")

    /**
     * Definition: 1 ngan = 100 square wa = 400 square meters.
     *
     * See
     * [Thai Agricultural Land Reform Office](https://alro.go.th/uploads/org/mukdahan/download/article/article_20190822204852.pdf).
     */
    @JvmField public val Ngan: AreaUnit = AreaUnit(400.0, "งาน")

    /**
     * Definition: 1 rai = 4 ngan = 1600 square meters.
     *
     * See
     * [Thai Agricultural Land Reform Office](https://alro.go.th/uploads/org/mukdahan/download/article/article_20190822204852.pdf).
     */
    @JvmField public val Rai: AreaUnit = AreaUnit(1_600.0, "ไร่")

    /**
     * Definition: 1 วา = 2.0 meters.
     *
     * See
     * [Thai government technical-college conversion chart](https://ctc.chontech.ac.th/files/2204271515202353_24051514142105.pdf).
     */
    @JvmField public val Wa: LengthUnit = LengthUnit(2.0, "วา", squaredUnit = SquareWa)
}
