// Generated by tools/units-generator. Edit catalog files in tools/units-generator and run mise run
// generate:units.
package org.maplibre.spatialk.units.catalog

import kotlin.jvm.JvmField
import org.maplibre.spatialk.units.LengthUnit

/**
 * Clarke units used in Trinidad and Tobago surveying. See the
 * [government surveying report (2000), pages 5 and 21](https://www.terrainstitute.org/lupap/lupap_pdf/S003.pdf).
 */
public data object TrinidadAndTobago {
    /**
     * Definition: Clarke foot, EPSG 9005: 0.3047972654 meters.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val ClarkeFeet: LengthUnit = LengthUnit(0.3047972654, "ft")

    /**
     * Definition: Clarke link, EPSG 9039: 0.201166195164 meters.
     *
     * See
     * [EPSG conversions in PROJ](https://github.com/OSGeo/PROJ/blob/047e5dbc74ef872828c06f24c6f67bb7b55432cf/data/sql/unit_of_measure.sql).
     */
    @JvmField public val ClarkeLinks: LengthUnit = LengthUnit(0.201166195164, "link")
}
