// Generated by tools/units-generator. Edit catalog files in tools/units-generator and run mise run
// generate:units.
package org.maplibre.spatialk.units.catalog

import kotlin.jvm.JvmField
import org.maplibre.spatialk.units.LengthUnit

/** British nautical lengths. */
public data object UK {
    /**
     * Definition: 1 Admiralty cable = 608 international feet.
     *
     * See
     * [IHO Hydrographic Dictionary, cable](https://portal.iho.int/iho-ohi/S32/engView.php?page=30).
     */
    @JvmField public val AdmiraltyCables: LengthUnit = LengthUnit(185.3184, "cable")
}
