// Generated by tools/units-generator. Edit catalog files in tools/units-generator and run mise run
// generate:units.
package org.maplibre.spatialk.units.catalog

import kotlin.jvm.JvmField
import org.maplibre.spatialk.units.AreaUnit
import org.maplibre.spatialk.units.LengthUnit
import org.maplibre.spatialk.units.catalog.US.SurveySquareFeet
import org.maplibre.spatialk.units.catalog.US.SurveySquareMiles
import org.maplibre.spatialk.units.catalog.US.SurveySquareRods

/**
 * U.S. units, including the survey-foot family for legacy data. The survey foot is 1200/3937
 * meters.
 */
public data object US {
    /**
     * Definition: 1 survey square foot = (1200/3937)² square meters.
     *
     * See
     * [NIST survey-foot conversions](https://www.nist.gov/pml/us-surveyfoot/revised-unit-conversion-factors).
     */
    @JvmField public val SurveySquareFeet: AreaUnit = AreaUnit(0.09290341161327482, "ft²")

    /**
     * Definition: 1 survey square rod = 272.25 survey square feet.
     *
     * See
     * [NIST survey-foot conversions](https://www.nist.gov/pml/us-surveyfoot/revised-unit-conversion-factors).
     */
    @JvmField public val SurveySquareRods: AreaUnit = AreaUnit(25.29295381171407, "rd²")

    /**
     * Definition: 1 survey acre = 43560 survey square feet.
     *
     * See
     * [NIST survey-foot conversions](https://www.nist.gov/pml/us-surveyfoot/revised-unit-conversion-factors).
     */
    @JvmField public val SurveyAcres: AreaUnit = AreaUnit(4_046.8726098742513, "acre")

    /**
     * Definition: 1 survey square mile = 27878400 survey square feet.
     *
     * See
     * [NIST survey-foot conversions](https://www.nist.gov/pml/us-surveyfoot/revised-unit-conversion-factors).
     */
    @JvmField public val SurveySquareMiles: AreaUnit = AreaUnit(2_589_998.4703195207, "mi²")

    /**
     * Definition: 1 survey foot = 1200/3937 meters.
     *
     * See
     * [NIST survey-foot conversions](https://www.nist.gov/pml/us-surveyfoot/revised-unit-conversion-factors).
     */
    @JvmField
    public val SurveyFeet: LengthUnit =
        LengthUnit(0.3048006096012192, "ft", squaredUnit = SurveySquareFeet)

    /**
     * Definition: 1 survey Gunter link = 0.66 survey feet.
     *
     * See
     * [NIST survey-foot conversions](https://www.nist.gov/pml/us-surveyfoot/revised-unit-conversion-factors).
     */
    @JvmField public val SurveyGunterLinks: LengthUnit = LengthUnit(0.20116840233680466, "link")

    /**
     * Definition: 1 survey rod = 16.5 survey feet.
     *
     * See
     * [NIST survey-foot conversions](https://www.nist.gov/pml/us-surveyfoot/revised-unit-conversion-factors).
     */
    @JvmField
    public val SurveyRods: LengthUnit =
        LengthUnit(5.029210058420117, "rod", squaredUnit = SurveySquareRods)

    /**
     * Definition: 1 survey Gunter chain = 66 survey feet.
     *
     * See
     * [NIST survey-foot conversions](https://www.nist.gov/pml/us-surveyfoot/revised-unit-conversion-factors).
     */
    @JvmField public val SurveyGunterChains: LengthUnit = LengthUnit(20.116840233680467, "ch")

    /**
     * Definition: 1 survey furlong = 660 survey feet.
     *
     * See
     * [NIST survey-foot conversions](https://www.nist.gov/pml/us-surveyfoot/revised-unit-conversion-factors).
     */
    @JvmField public val SurveyFurlongs: LengthUnit = LengthUnit(201.16840233680466, "fur")

    /**
     * Definition: 1 survey mile = 5280 survey feet.
     *
     * See
     * [NIST survey-foot conversions](https://www.nist.gov/pml/us-surveyfoot/revised-unit-conversion-factors).
     */
    @JvmField
    public val SurveyMiles: LengthUnit =
        LengthUnit(1_609.3472186944373, "mi", squaredUnit = SurveySquareMiles)

    /**
     * Definition: 1 survey land league = 15840 survey feet.
     *
     * See
     * [NIST survey-foot conversions](https://www.nist.gov/pml/us-surveyfoot/revised-unit-conversion-factors).
     */
    @JvmField public val SurveyLandLeagues: LengthUnit = LengthUnit(4_828.041656083312, "lea")

    /**
     * Definition: 1 survey fathom = 6 survey feet.
     *
     * See
     * [NIST survey-foot conversions](https://www.nist.gov/pml/us-surveyfoot/revised-unit-conversion-factors).
     */
    @JvmField public val SurveyFathoms: LengthUnit = LengthUnit(1.828803657607315, "fathom")

    /**
     * Definition: 1 survey cable = 720 survey feet.
     *
     * See
     * [NIST survey-foot conversions](https://www.nist.gov/pml/us-surveyfoot/revised-unit-conversion-factors).
     */
    @JvmField public val SurveyCables: LengthUnit = LengthUnit(219.45643891287781, "cable")

    /**
     * Definition: 1 customary cable = 720 international feet.
     *
     * See
     * [NIST survey-foot conversions](https://www.nist.gov/pml/us-surveyfoot/revised-unit-conversion-factors).
     */
    @JvmField public val CustomaryCables: LengthUnit = LengthUnit(219.456, "cable")
}
