name: Publish Website

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write

jobs:
    publish-website:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - name: Build Dokka docs
              run: ./gradlew dokkaGenerateHtml

            - name: Build mkdocs
              run: |
                  pip3 install mkdocs-material
                  mkdocs build

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@releases/v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: gh-pages
                  folder: site
                  single-commit: true
